# Generated by Django 3.1.14 on 2022-09-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20220917_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchrunmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='batchrunmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
