# Generated by Django 3.1.14 on 2022-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220918_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
